FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps

# ✅ Accept build arguments
ARG VITE_JYOTI_PASSWORD
ARG VITE_RITESH_PASSWORD
ARG VITE_SHALINI_PASSWORD
ARG VITE_RINKU_PASSWORD
ARG VITE_BABLOO_PASSWORD

# ✅ Set them as environment variables so Vite can read them
ENV VITE_JYOTI_PASSWORD=$VITE_JYOTI_PASSWORD
ENV VITE_RITESH_PASSWORD=$VITE_RITESH_PASSWORD
ENV VITE_SHALINI_PASSWORD=$VITE_SHALINI_PASSWORD
ENV VITE_RINKU_PASSWORD=$VITE_RINKU_PASSWORD
ENV VITE_BABLOO_PASSWORD=$VITE_BABLOO_PASSWORD

COPY . .
RUN npm run build

CMD ["npm", "start"]