import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateReceiptPDF = (form, preview = false) => {
  const doc = new jsPDF();

  const now = new Date();
  const currentDate = now.toISOString().split("T")[0]; // YYYY-MM-DD

  // Convert to 12-hour format
  const rawTime = now.toTimeString().split(" ")[0]; // HH:MM:SS
  const [hours, minutes, seconds] = rawTime.split(":");
  const hh = parseInt(hours);
  const ampm = hh >= 12 ? "PM" : "AM";
  const formattedHour = hh % 12 || 12;
  const currentTime = `${formattedHour}:${minutes}:${seconds} ${ampm}`;

  const username = sessionStorage.getItem("username") || "Unknown";

  // Header
  doc.setFontSize(16);
  doc.setTextColor(204, 0, 0);
  doc.text("K.K. HOSPITAL, LUCKNOW", 20, 15);

  doc.setFontSize(10);
  doc.setTextColor(0);
  doc.text("Address: 87/88, Nabiullah Road, Opp. SSP Office, River Bank Colony, Lucknow", 20, 21);
  doc.text("Phone: 0522-2619049/50 & 2231932, Email: kkhospitallko1991@gmail.com", 20, 26);
  doc.text("GSTIN: 09AAATK4016C2ZZ, Reg. No.: 0915700003", 20, 31);

  doc.setFontSize(13);
  doc.setTextColor(33, 150, 243);
  doc.text("TRANSACTION SUMMARY", 70, 40);

  // Main Table
  const rows = [
    ["Transaction No.", form.transaction_no],
    ["Patient UHID", form.patient_uhid],
    ["Patient Reg. No.", form.patient_regno],
    ["Patient Name", form.patient_name],
    ["Admission Date", form.admission_date],
    ["Payment Mode", form.payment_mode],
    ["Amount (In Figures)", `Rs. ${form.amount}`],
  ];

  if (form.payment_mode === "CHEQUE" && form.payment_details) {
    rows.push(
      ["Bank Name", form.payment_details.bank_name || "-"],
      ["Cheque No.", form.payment_details.cheque_number || "-"],
      ["Cheque Date", form.payment_details.cheque_date || "-"]
    );
  }

  autoTable(doc, {
    startY: 45,
    theme: "grid",
    head: [["Details", "Information"]],
    body: rows,
    columnStyles: {
      0: { cellWidth: 60 },
      1: { cellWidth: 110 },
    },
  });

  // Purpose of Transaction
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["Purpose of Transaction"]],
    body: [[form.transaction_purpose || ""]],
    theme: "grid",
    styles: { fontSize: 10 },
  });

  // Footer Notes
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0);
  const baseY = doc.lastAutoTable.finalY;

  doc.text("Declaration:", 14, baseY + 15);
  doc.setFontSize(9);
  doc.text(
    "This is a computer-generated document. Please retain this for your records.",
    14,
    baseY + 20
  );

  doc.setFontSize(10);
  doc.text("Authorized Signatory:", 14, baseY + 35);
  doc.text(`Transaction Date & Time: ${currentDate} ${currentTime}`, 14, baseY + 42);
  doc.text(`Generated by: ${username}`, 14, baseY + 49);

  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text("Note: We receive payment at reception only", 14, baseY + 60);

  // Output
  if (preview) {
    const pdfBlob = doc.output("blob");
    const pdfUrl = URL.createObjectURL(pdfBlob);
    window.open(pdfUrl); // opens in new tab
  } else {
    doc.save(`receipt_${form.transaction_no}.pdf`);
  }
};
