import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateReceiptPDF = (form, preview = false) => {
  const doc = new jsPDF();

  const now = new Date();
  // const currentDate = now.toISOString().split("T")[0]; // YYYY-MM-DD

  // Convert to 12-hour format
  const rawTime = now.toTimeString().split(" ")[0]; // HH:MM:SS
  const [hours, minutes, seconds] = rawTime.split(":");
  const hh = parseInt(hours);
  const ampm = hh >= 12 ? "PM" : "AM";
  const formattedHour = hh % 12 || 12;
  const currentTime = `${formattedHour}:${minutes}:${seconds} ${ampm}`;

  const username = sessionStorage.getItem("username") || "Unknown";

  // Header
  doc.setFontSize(16);
  doc.setTextColor(204, 0, 0);
  doc.text("K.K. HOSPITAL, LUCKNOW", 20, 15);

  doc.setFontSize(10);
  doc.setTextColor(0);
  doc.text("Address: 87/88, Nabiullah Road, Opp. SSP Office, River Bank Colony, Lucknow", 20, 21);
  doc.text("Phone: 0522-2619049/50 & 2231932", 20, 26);
  doc.text("Email: kkhospitallko1991@gmail.com, contact@kkhospitallucknow.com", 20, 31);
  doc.text("GSTIN: 09AAATK4016C2ZZ, Registration Number: 0915700003", 20, 37);
  doc.text("___________________________________________________________________________________", 20, 40 );


  doc.setFontSize(13);
  doc.setTextColor(33, 150, 243);
  doc.text("TRANSACTION SUMMARY", 70, 55);

  // Main Table
  const rows = [
    ["Transaction No.", form.transaction_no],
    ["Patient UHID", form.patient_uhid],
    ["Patient Reg. No.", form.patient_regno],
    ["Patient Name", form.patient_name],
    ["Admission Date", form.admission_date],
    ["Payment Mode", form.payment_mode],
    ["Amount (In Figures)", `Rs. ${Number(form.amount).toLocaleString('en-IN', {
      maximumFractionDigits: 2,
      minimumFractionDigits: 2
    })}`],
  ];

  if (form.payment_mode === "CHEQUE" && form.payment_details) {
    rows.push(
      ["Bank Name", form.payment_details.bank_name || "-"],
      ["Cheque No.", form.payment_details.cheque_number || "-"],
      ["Cheque Date", form.payment_details.cheque_date || "-"]
    );
  }

  autoTable(doc, {
    startY: 65,
    theme: "grid",
    head: [["Details", "Information"]],
    body: rows,
    columnStyles: {
      0: { cellWidth: 60 },
      1: { cellWidth: 110 },
    },
  });

  // Purpose of Transaction
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["Purpose of Transaction"]],
    body: [[form.transaction_purpose || ""]],
    theme: "grid",
    styles: { fontSize: 10 },
    columnStyles: {
      0: { cellWidth: 171 },
      // 1: { cellWidth: 110 },
    },
  });

  // Footer Notes
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  const baseY = doc.lastAutoTable.finalY;

  doc.text("Declaration:", 14, baseY + 15);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");

  doc.text(
    "This is a computer-generated document. Please retain this for your records.",
    14,
    baseY + 20
  );

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Authorized Signatory:", 14, baseY + 35);
  doc.setFont("helvetica", "normal");
  doc.text("_______________________", 60, baseY + 35);

  doc.setFont("helvetica", "bold");
  doc.text("Transaction Date:", 14, baseY + 42);
  doc.setFont("helvetica", "normal");
  doc.text(`${form.transaction_date}`, 50, baseY + 42);

  doc.setFont("helvetica", "bold");
  doc.text("Transaction Time:", 14, baseY + 49);
  doc.setFont("helvetica", "normal");
  doc.text(`${currentTime}`, 50, baseY + 49);

  doc.setFont("helvetica", "bold");
  doc.text("Generated by:", 14, baseY + 56);
  doc.setFont("helvetica", "normal");
  doc.text(username, 43, baseY + 56);

  doc.setFontSize(8);
  doc.setFont("helvetica", "italic", "bold");

  doc.text("Note: We receive payment at reception only", 14, baseY + 67);

  // Output
  if (preview) {
    const pdfBlob = doc.output("blob");
    const pdfUrl = URL.createObjectURL(pdfBlob);
    window.open(pdfUrl); // opens in new tab
  } else {
    doc.save(`receipt_${form.transaction_no}.pdf`);
  }
};
