import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { LogoBase64 } from "./Logo";

export const generatePatientPDF = (patient, preview = false) => {
  console.log("Generating Patient PDF with data:", patient);
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

    const now = new Date();
  // const currentDate = now.toISOString().split("T")[0]; // YYYY-MM-DD

  // Convert to 12-hour format
  const rawTime = now.toTimeString().split(" ")[0]; // HH:MM:SS
  const [hours, minutes, seconds] = rawTime.split(":");
  const hh = parseInt(hours);
  const ampm = hh >= 12 ? "PM" : "AM";
  const formattedHour = hh % 12 || 12;
  const currentTime = `${formattedHour}:${minutes}:${seconds} ${ampm}`;

  const username = sessionStorage.getItem("username") || "Unknown";

  // ---------------- HEADER ----------------
  doc.addImage(LogoBase64, "PNG", pageWidth - 40, 15, 20, 20);

  doc.setFontSize(16);
  doc.setTextColor(204, 0, 0);
  doc.text("K.K. HOSPITAL, LUCKNOW", 20, 15);

  doc.setFontSize(10);
  doc.setTextColor(0);
  doc.text(
    "Address: 87/88, Nabiullah Road, Opp. SSP Office, River Bank Colony, Lucknow",
    20,
    21
  );
  doc.text("Phone: 0522-2619049/50 & 2231932", 20, 26);
  doc.text(
    "Email: kkhospitallko1991@gmail.com, contact@kkhospitallucknow.com",
    20,
    31
  );
  doc.text("GSTIN: 09AAATK4016C2ZZ, Registration Number: 0915700003", 20, 37);
  doc.text(
    "___________________________________________________________________________________",
    20,
    40
  );

  doc.setFontSize(13);
  doc.setTextColor(33, 150, 243);
  doc.text("REGISTRATION SUMMARY", 75, 55);

  const rows = [
    ["UHID / Reg No", patient.uhid +" / "+ patient.regno],
    ["Name", `${patient.title || ""} ${patient.fullname || ""}`],
    ["Patient Type", patient.patient_type || "-"],
    ["Registration Amount", patient.regAmount || "-"],
    ["Registration Date", patient.dateofreg || "-"],
    ["Registration Time", patient.time || "-"],
    ["Age", patient.age || "-"],
    ["Sex", patient.sex || "-"],
    ["Mobile Number", patient.mobile || "-"],
    ["Aadhaar Number", patient.adhaar_no || "-"],
    ["Religion", patient.religion || "-"],
    ["Marital Status", patient.maritalStatus || "-"],
    ["Father / Husband", patient.fatherHusband || "-"],
    ["Doctor(s)", (patient.doctorIncharge || []).join(", ") || "-"],
    [
      "Local Address",
      `${patient.localAddress?.address || ""}, ${
        patient.localAddress?.city || ""
      }`,
    ],
    [
      "Permanent Address",
      `${patient.permanentAddress?.address || ""}, ${
        patient.permanentAddress?.city || ""
      }`,
    ],
  ];

  autoTable(doc, {
    startY: 60,
    head: [["Field", "Value"]],
    body: rows,
    theme: "grid",
  });

  // Footer Notes
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  const baseY = doc.lastAutoTable.finalY;

  doc.text("Declaration:", 14, baseY + 15);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");

  doc.text(
    "This is a computer-generated document. Please retain this for your records.",
    14,
    baseY + 20
  );

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Authorized Signatory:", 14, baseY + 35);
  doc.setFont("helvetica", "normal");
  doc.text("_______________________", 60, baseY + 35);

  doc.setFont("helvetica", "bold");
  doc.text("Printing Date:", 14, baseY + 42);
  doc.setFont("helvetica", "normal");
  doc.text(`${patient.dateofreg}`, 50, baseY + 42);

  doc.setFont("helvetica", "bold");
  doc.text("Printing Time:", 14, baseY + 49);
  doc.setFont("helvetica", "normal");
  doc.text(`${currentTime}`, 50, baseY + 49);

  doc.setFont("helvetica", "bold");
  doc.text("Generated by:", 14, baseY + 56);
  doc.setFont("helvetica", "normal");
  doc.text(username, 43, baseY + 56);

  doc.setFontSize(8);
  doc.setFont("helvetica", "italic", "bold");

  doc.text("Note: We receive payment at reception only", 14, baseY + 67);


  // doc.save(`patient_${patient.uhid}.pdf`);

  if (preview) {
    const pdfBlob = doc.output("blob");
    const pdfUrl = URL.createObjectURL(pdfBlob);
    window.open(pdfUrl);
  } else {
    doc.save(`bill_${billData[0].final_bill_no || "NA"}.pdf`);
  }
};
